# Navigation Links
# The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Topics
    url: categories/
    identifier: categories
    weight: 20
  - name: Tehillim
    parent: categories
    url: categories/tehillim
    weight: 21
  - name: Parasha
    parent: categories
    url: categories/parasha
    weight: 22
    
#  - name: Tehillim
#    identifier: cat_tehillim
#    weight: 30
#  - name: Tehillims
#    parent: categories
#    url: categories/tehillim/
#    weight: 40
#  - name: Uses
#    url: uses/d
#    weight: 30
