# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Topics
    url: categories/
    identifier:categories
    weight: 20

- name: Tehillim
    parent: categories
    url: categories/tehillim/
    weight: 10
#  - name: Uses
#    url: uses/
#    weight: 30
